# Generated by Django 5.0.1 on 2025-03-05 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_file_id',
            field=models.CharField(default=datetime.datetime(2025, 3, 5, 16, 59, 48, 36613, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='resume_file_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
